### PR TITLE
Home screen

### PR DESCRIPTION
**Pull request by sindunarasimhan**
Default Navigation Drawer which loads basic couple dashboard on click. I made the color material blue, to just see if you guys like it. I can change it back to the design default if it is Meh ! 

TODO: Customize navigation drawer elements
             Add elements to couple dashboard view

This is how the current implementation looks like. 
screenshot_2015-06-30-10-46-48
screenshot_2015-06-30-10-47-00

### CODE REVIEW

**Comment by AllieDeford** [comment]
This looks good. Are you still working on other things for this PR or do you want to merge?

**Comment by sindunarasimhan** [comment]
I think we can go ahead and merge this if you feel it is ok. I was thinking
of getting the screen bare bones together and then go in and customize them
each in the next few weeks as side work.

**Comment by AllieDeford** [comment]
However you want to manage your workflow is fine with me. I tend to make a lot of changes per pull request unless it's an explicit bug fix or I know another person is waiting on it, so I figured I'd double check if you were ready for merge. 

In the future, let's do this-- when we're ready for the other one to review and merge, let's use GitHub's assign feature and assign them the pull request so we know they're ready. Sound good?

**Comment by sindunarasimhan** [comment]
That is awesome. Also I have this backlog of enhancements I want to get back to, so I will create issues for them. Let me know when you have a chance to do a pull if nothing bizarre happened in your environment

**Comment by AllieDeford** [comment]
I probably won't try to merge your changes with my branch until I'm done building things, but I'll do it before I submit a pull

**Pull request merged**
