### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by sindunarasimhan**
I had changed the viral load activity earlier, but for now, decided to redo the changes of the previous version. I was apprehensive about just not adding the files to the commit, as I cant test them, so I redid the changes and pushed this one. Added a few async tasks for db fetches. 

Issues it covers 
#22, #35 , #31

### CODE REVIEW

**Comment by AllieDeford** [comment]
@sindunarasimhan can you merge in the current master for this one?

**Comment by sindunarasimhan** [comment]
sure

**Comment by sindunarasimhan** [comment]
if you've had a chance to look at it, and are ok with the current changes, Ill add in some new commits and merge in all together. The calendar refresh is working now, and I also have the participant perspectives currently in dev. Let me know if you feel otherwise.

**Comment by AllieDeford** [comment]
that's fine

On Mon, Aug 17, 2015 at 10:35 AM, sindunarasimhan notifications@github.com
wrote:

> if you've had a chance to look at it, and are ok with the current changes,
> Ill add in some new commits and merge in all together. The calendar refresh
> is working now, and I also have the participant perspectives currently in
> dev. Let me know if you feel otherwise.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SCIP-app/androidApp/pull/43#issuecomment-131900213.

## 

Allie Deford
Human Centered Design and Engineering M.S. Candidate
(765) 404-8702
alliedeford.me

**Pull request closed without merging**
