### PR TITLE
Changed the default main activity to a login activity. Login activity…

### PR DESCRIPTION
**Pull request by sindunarasimhan**
… has some basic checks for email format and if the password is a 4 letter password. Pretty much enter anything in this screen and it takes you to a list view of coupleids. Currently dummied up with text that reads itemID

### CODE REVIEW

**Comment by AllieDeford** [comment]
It appears we are using different versions of Java, different versions of gradle, and I selected different versions of Android. I'm going to accept and try this, but I'm not confident everything isn't going to explode

**Comment by sindunarasimhan** [comment]
Urg !!!! Tell me how it goes... Keeping fingers crossed !!!!

**Comment by AllieDeford** [comment]
I finally got the project to properly build without needing to change any of the files, but I'm having problems getting the emulator to work. Have you found a good AVD for this project?

**Comment by sindunarasimhan** [comment]
Phew. That is great. With my version I have always had trouble getting the
emulator to work. I borrowed a tablet from Kristin. I don't think I'll use
that till next Wednesday and can hand it over if you want it.

I did find mdpi  and ldpi emulators to at least launch but hdpi emulatora
have always crashed on me. But I have an old 4gig Mac however so if you
have more Ram you might be at luck with the other.

**Pull request merged**
